sudo: required

services:
- docker

before_install:
- docker pull teamdfir/sift-salt-tester:bionic

script:
- ./scripts/test.sh

after_success:
- ./scripts/publish-draft.sh

env:
  matrix:
    - TEST_SIFT_VERSION=stable
  global:
    secure: OOeIrkKyv4vFGkwpiUYJWJyI2lOhyCxFd5p/0+4vGwWh3NzL3AXfc6GcUBogCqG+LAz+qz9IzwSxjhzswKaPnBArEWf7hov3Z4Lq8pUR5Uywpqww13RoTtyK2xOMLYZpYfLLh/8RQG6RSVj7bAQfiurrq4HoM9Np1ALzOhreTptQ5OJdpnj5Nlxty6azL7tqHCxlOZI6Kg24nVS4KZcwMhoqlWpfH0WnhbTdlS63DwhqgsEa0VIANwmvfDYoXDvRPPAW5UJ0Ij+ZJi5MLb65sGZLIYz8La/BknfFbpTvyXnacz3WSrk/yThU0bZzCgAWb5hXrOPOUHnsadO/hA4XZ3ovwfcTYDLgw5iZHT4oCDVQMX8rGK2/Xae1FSoYSCRxXNgwx3SQf2tOj385Xn6/TPJN9LZFIzzEC2YDBN/aXMNHXpbgyYDLAHD78rxLO4zWP+oJn5mMKeg6ElowAMX7Zr6KjoxlQY+OuyZxlWYwwzhjyP40S5hiWy6aHnwADFQyYS202XjsYFblpG03NR9hj1HIS+Yg21NgLNRu1okNBSFNpPAGww6MLypmXEXEj0nJlOylWkfIdu2flS9vKxnkndYG5z1U803DnGk48nbAxRZhU9W2Q2UPB7HKGyrw0dm5ERCbvDpZIa0Hxk7c/3y7aY4QQTj+lSj0ALeF+71HRoU=
